import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "./Components/Footer/page";
import Header from "./Components/Header/page";
import Head from "next/head";
import Script from "next/script";

import { localFont } from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "مستشارك",
  description: "Generated by create next app",
};

const tajawal = localFont({
  src: [{ path: "../public/Fonts/Tajawal-Bold.ttf", weight: "700" }],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="ar" className={tajawal.className}>
      <head>
        <link rel="icon" type="image/png" href="/img/Avatar.png" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Google Analytics */}
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-PVEZ8977CT"
        />

        <Script id="ga-script">
          {`
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-PVEZ8977CT');
`}
        </Script>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
