import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "./Components/Footer/page";
import Header from "./Components/Header/page";
import Head from "next/head";
import { localFont } from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "مستشارك",
  description: "Generated by create next app",
};

const tajawal = localFont({
  src: [{ path: "../public/fonts/Tajawal-Bold.ttf", weight: "700" }],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="ar" className={tajawal.className}>
      <Head>
        <link rel="icon" type="image/png" href="/img/Avatar.png" />
      </Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
